### ISSUE TITLE
Error in minisatip ebuild

### ISSUE THREAD

**Issue by helau** [3PO/3PO-overlay#1]
in src_prepare the line:
          sed -i "${S}"/Makefile -e "s/DVBCSA?=yes/DVBCSA?=no/" || die
fails, because no Makefile is available, only makefile.in

**Comment by 3PO** [comment]
Fixed!

--> https://github.com/3PO/3PO-overlay/commit/0ed7273265f0d9ea98e48d971275a98e7bb60b8b
