### ISSUE TITLE
Remove dependency from mysql

### ISSUE THREAD

**Issue by helau** [3PO/3PO-overlay#6]
To use mariadb instead of mysql (whats the gentoo preference) change in epgd-9999.ebuild the line:

	>=dev-db/mysql-5.1.70

to

	>=virtual/mysql-5.1.70

**Comment by 3PO** [comment]
Fixed.  --> https://github.com/3PO/3PO-overlay/commit/46f9f1c0f87efc32d5538508197943ecb1f49216
